
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://rovermodernretail.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: 

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Robert James"
title: "Rover"
description: "Modern retail."
keywords: "rover, modern, retail, robert"
favicon: "/img/rovercart.ico"

################
# Header layout #
################

black-favicon: "/img/RoverCart16.png"

background-img: "/img/Umbrellas_at_Caudan_Waterfront_Mall.JPG"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 9
start-delay: 200
delete-delay: 4900
lines: # You can add HTML Tags in the Text
 - text: "<font size= 7 font color= white> Real-time inventory searchability </font>"
 - text: "<font size= 7 font color= white> Mobile checkoutingness </font>"

me-img: "/img/rovercart.png"

##############################
# Color the browser elements #
##############################
color-browser: "#F0F7FF"
apple-status-bar-style: "ghost white"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 4

email-share: False
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: False
vkontakte-share: False

disqus-shortname: "Rover"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "2016"
    description: "Rover was Born"
  - image: "/img/timeline/first-rover-logo.png"
    date: "August 2016 - Today"
    description: "App Development"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: robert@rovermodernretail.com

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Robert is a marketing student at UAB that isn't quite sure of what all is going on. In his spare time, he likes to pretend he knows enough HTML to make a website."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/rovermodernretail"
    
############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: Rovermodern
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
